### ISSUE TITLE
 setOnHashtagClickListener() Problem & Missing Packages for 0.2 Version

### ISSUE THREAD

**Issue by haolam98** [hendraanggrian/socialview#103]
Hello,
I tried to get the basic SocialTextView for my hashtags list. For example, SocialTextView will contain: "#abc #efg #123 #fghh #iop". And I want to make it clickable on every hashtag in the SocialTextView. 

I followed the readme file but get some trouble with setOnHashtagClickListener().Please help! Thanks
<img width="1516" alt="Screen Shot 2021-06-13 at 02 32 11" src="https://user-images.githubusercontent.com/43900929/121802080-a02f2a80-cbef-11eb-9e05-38d074aef281.png">

I think there is only Function2 method suggest for setOnHashtagClickListener(). And I believe this method is for Kotlin, not java. I cannot work with this method since it requires a return of Unit object?
<img width="1006" alt="Screen Shot 2021-06-13 at 02 47 16" src="https://user-images.githubusercontent.com/43900929/121802525-ad4d1900-cbf1-11eb-881e-addf9a9bc28e.png">

Also, I cannot update to latest version (0.2) due to some packages does not exist too. I'm currently in version 0.1
<img width="1450" alt="Screen Shot 2021-06-13 at 02 49 18" src="https://user-images.githubusercontent.com/43900929/121802583-f604d200-cbf1-11eb-84d2-354b7dca8a6b.png">

**Comment by hendraanggrian** [comment]
I think you're pulling the artifacts from jcenter, which is deprecated by now. Try adding [Sonatype's snapshots repository](https://s01.oss.sonatype.org/content/repositories/snapshots/) and use version `0.1-SNAPSHOT`.

**Comment by haolam98** [comment]
Sorry, I'm new to this stuff. How can I add the Sonatype repository to my Android Studio project? 
I tried to add the Sonatype repo in the Gradel Project, however, I still get the unresolve NonNull error on the setOnHashtagClickListener() function

Below are my Gradle App and Gradle Project file & the error I got on my Android Studio project:

<img width="991" alt="Screen Shot 2021-07-12 at 11 25 25" src="https://user-images.githubusercontent.com/43900929/125230854-de5d5e00-e303-11eb-8a37-70035720abe8.png">
<img width="970" alt="Screen Shot 2021-07-12 at 11 26 11" src="https://user-images.githubusercontent.com/43900929/125230919-f7fea580-e303-11eb-932e-ab8f8185eab4.png">
<img width="1035" alt="Screen Shot 2021-07-12 at 11 26 45" src="https://user-images.githubusercontent.com/43900929/125230961-0cdb3900-e304-11eb-8542-b1b21248c90a.png">

Thanks

**Comment by hendraanggrian** [comment]
In your root `build.gradle`:

```gradle
allprojects {
    repositories {
        maven { url "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/" }
    }
}
```

Then change the version of the library from `0.2` to `0.1-SNAPSHOT`.

**Comment by mahbub-java** [comment]
why jitpack version not working....
https://jitpack.io/p/hendraanggrian/socialview
