### ISSUE TITLE
Auto complete view showing for seconds for hashtag

### ISSUE THREAD

**Issue by thedeveloper19** [hendraanggrian/socialview#104]
I'm implemented autocomplete text view with some hashtag

But when type suggestions are showing as blink. I mean its not sticking. Just sowing for less than a seconds

**Comment by hendraanggrian** [comment]
Can you share your code or your test case? I need to reproduce the exact error in order to investigate.

**Comment by hendraanggrian** [comment]
Closed for inactivity.
