### ISSUE TITLE
setHashtagTextChangedListener and AutoComplete

### ISSUE THREAD

**Issue by azelas** [hendraanggrian/socialview#105]
Hello, First of all thanks for this library!
I've pretty much set everything up correctly. 
1. I used SocialAutoCompleteTextView - Done
2. I wanted to use my own REST Api to populate the hashtag list - Done
3. I made my own adapter that extends ArrayAdapter. The SocialArrayAdapter was filtering the list before the list was made.
4. I used text.setHashtagTextChangedListener .  I didn't really need a filter because as I type something, my app searches.

5. I'm stuck here, when I click the dropdown list of hashtags. When I click on a hashtag, it doesn't load the hashtag name I set but rather my model name and it searches that model name.

What I'm looking for....Type and have suggestions of hashtags. Click on hashtag in suggestions list and continue typing other non-hashtag words for ex. John #loves playing #tennis.  I don't know what I'm missing, do I need something from the SocialArrayAdapter I missed?
`

        et_des.setHashtagTextChangedListener(new SocialView.OnChangedListener() {
            @Override
            public void onChanged(@NonNull SocialView view, @NonNull CharSequence text) {
                presenter.getHashtags(text.toString());
                
                

            }
        });
        et_des.setOnHashtagClickListener(new SocialView.OnClickListener() {
            @Override
            public void onClick(@NonNull @NotNull SocialView view, @NonNull @NotNull CharSequence text) {
                //do nothing
            }
        });
        et_des.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                Toast.makeText(getApplicationContext(), list_tags2.get(position).getTag_name(), Toast.LENGTH_LONG).show();
            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {

            }
        });
        et_des.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
               // Toast.makeText(getApplicationContext(), list_tags2.get(position).getTag_name(), Toast.LENGTH_LONG).show();
                //Save hashtag to list
            }
        });`

**Comment by hendraanggrian** [comment]
I'm still struggling to understand point 5:

> I'm stuck here, when I click the dropdown list of hashtags. When I click on a hashtag, it doesn't load the hashtag name I set but rather my model name and it searches that model name.

Can you explain what your model is? Your custom model should override `toString` method. If you can see in `SocialArrayAdapter#convertToString`, any hashtagable or mentionable object would be converted to string and that string should pop out in your TextView.

**Comment by azelas** [comment]
Hi. Thanks for getting back to me. 

Some changes that I've made..I put the server request in my performing filter. The issue that I'm having now is that list is shown and disappears very quickly. I don't know what I'm doing wrong. I've debugged it and after showing in getView , the program goes to getCount. Here is shows the list and after getCount the list disappears.


 `public class HashtagAdapter extends SocialArrayAdapter<TagModel> {

    private List<TagModel> list;
    REST rest;
    Context context;

    public HashtagAdapter(@NonNull Context context) {
        super(context, R.layout.layout_tag, R.id.tag_name);
        rest = new REST(context);
        this.context = context;
    }


    @NonNull
    @Override
    public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent) {
        ViewHolder holder;
        if (convertView == null) {
            LayoutInflater inflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            convertView = inflater.inflate(R.layout.layout_tag, parent, false);
            holder = new ViewHolder(convertView);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }
//        TagModel item = getItem(position);
        TagModel item = list.get(position);
        if (item != null) holder.textView.setText(item.getTag_name());
        return convertView;
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Nullable
    @Override
    public TagModel getItem(int position) {
        return list.get(position);
    }

    @Override
    public int getCount() {
        return list.size();
    }

    @NonNull
    @Override
    public Filter getFilter() {
        return hashTagFilter;
    }

    private static class ViewHolder {
        final TextView textView;

        ViewHolder(@NonNull View view) {
            this.textView = view.findViewById(R.id.tag_name);
        }
    }


    private final Filter hashTagFilter = new Filter() {

        @Override
        protected FilterResults performFiltering(CharSequence constraint) {
            FilterResults results = new FilterResults();

            if (TextUtils.isEmpty(constraint)) {
                return results;
            }
            final List<TagModel> serverItems = findtagsNow(constraint.toString().substring(1));

//            final List<TagModel> suggestions = new ArrayList<>();
//            for (TagModel item : serverItems) {
//                if (convertResultToString(item)
//                        .toString()
//                        .toLowerCase(Locale.getDefault())
//                        .contains(constraint.toString().toLowerCase(Locale.getDefault()))) {
//                    suggestions.add(item);
//                }
//            }
//            results.values = suggestions;
//            results.count = suggestions.size();
//            return results;
            results.values = serverItems;
            results.count = serverItems.size();
            return results;
        }

        @Override
        protected void publishResults(CharSequence constraint, FilterResults results) {

            if (results != null && results.count > 0) {
                list = (List<TagModel>) results.values;

//                HashtagAdapter.super.clear();
//                for (final TagModel object : list) {
//                    HashtagAdapter.super.add(object);
//                }
//                HashtagAdapter.super.addAll(list);

                notifyDataSetChanged();
            } else {
                notifyDataSetInvalidated();

            }
        }

        @Override
        public CharSequence convertResultToString(Object resultValue) {
            return ((TagModel) resultValue).getTag_name();
        }
    };


    private List<TagModel> findtagsNow(String userinput) {
        Map<String, String> params = new HashMap<>();
        params.put("table", "get_hashtags");
        params.put("value1", userinput);

        return rest.tag_list(params);
    }
}
`

**Comment by hendraanggrian** [comment]
Sorry for late reply. If the dropdownlist disappears without you interacting it, then it suggests a misbehavior of the adapter. From the code you share, I'd say maybe don't implement your own filtering logic as `SocialArrayAdapter` already has them. See `HashtagArrayAdapter` for example.
