### ISSUE TITLE
mention with dot pattern

### ISSUE THREAD

**Issue by iranandroid** [hendraanggrian/socialview#106]
Hi
I need pattern to show mention with dot or without dot; like:
@test
@test.b

can help me?

**Comment by palVikas9** [comment]
I am stuck with the same issue

Can we create some custom implementation for that @hendraanggrian

**Comment by hendraanggrian** [comment]
Yes this is achievable by providing your own pattern, e.g.: `textView.setMentionPattern(pattern)`.

Now I'm not an expert of regex, you should consult that to StackOverflow. Ask them a pattern that accepts any texts divided by any number of dots.
