### ISSUE TITLE
can someone help me to solve this problem 

### ISSUE THREAD

**Issue by saurav12bisht** [hendraanggrian/socialview#107]
FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.hendraanggrian.appcompat:socialview:0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/hendraanggrian/appcompat/socialview/0.2/socialview-0.2.pom
       - https://repo.maven.apache.org/maven2/com/hendraanggrian/appcompat/socialview/0.2/socialview-0.2.pom
       - https://jitpack.io/com/hendraanggrian/appcompat/socialview/0.2/socialview-0.2.pom
     Required by:
         project :app
   > Could not find com.hendraanggrian.appcompat:socialview-commons:0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/hendraanggrian/appcompat/socialview-commons/0.2/socialview-commons-0.2.pom
       - https://repo.maven.apache.org/maven2/com/hendraanggrian/appcompat/socialview-commons/0.2/socialview-commons-0.2.pom
       - https://jitpack.io/com/hendraanggrian/appcompat/socialview-commons/0.2/socialview-commons-0.2.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

--------------------------------   Depedency i have used -----------------------------------------

implementation "com.hendraanggrian.appcompat:socialview:0.2"
    implementation "com.hendraanggrian.appcompat:socialview-commons:0.2"

**Comment by hendraanggrian** [comment]
Add maven url `https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/` to `allrepository/dependencies` and change version to `0.1-SNAPSHOT`.

**Comment by saurav12bisht** [comment]
Class referenced in the layout file, com.hendraanggrian.appcompat.widget.SocialAutoCompleteTextView, was not found in the project or the libraries
Cannot resolve class com.hendraanggrian.appcompat.widget.SocialAutoCompleteTextView

------------------------------i created this text view and its marking it red-------------------------------
 <com.hendraanggrian.appcompat.widget.SocialAutoCompleteTextView

                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/search_bar"
                android:background="@android:color/transparent"
                android:hint="Search..."
                android:layout_marginStart="10dp"/>

**Comment by hendraanggrian** [comment]
Open project tab in your IntelliJ Idea/Android Studio. On the end of the list there should be `External Libraries`, make sure you see `socialview-commons` there. Otherwise, the library has not yet been pulled.

![Screen Shot 2021-08-05 at 20 04 56](https://user-images.githubusercontent.com/11507430/128354664-5c0cf9b0-5146-41c8-810b-2f374e19155e.png)

**Comment by hendraanggrian** [comment]
Closed due to inactivity.
