### ISSUE TITLE
 implementation error

### ISSUE THREAD

**Issue by eiadhr5yp** [hendraanggrian/socialview#108]
Hello there so iwas trying to  implementation "com.hendraanggrian.appcompat:socialview:0.2" but igot an error 
Failed to resolve: com.hendraanggrian.appcompat:socialview-commons:0.2
Failed to resolve: com.hendraanggrian.appcompat:socialview:0.2
iwant to fix this error pls

**Comment by enesarisoy** [comment]
i solved it. All u need to do add this code to `build.gradle` and synchronize.

`allprojects {
    repositories {
        jcenter()
    }
}`
