### ISSUE TITLE
No ellipsize applied to SocialTextView

### ISSUE THREAD

**Issue by OneManStudioDotSe** [hendraanggrian/socialview#111]
Thanks for this very useful library :)

I am facing a strange issue. I have a SocialTextView where I also want to apply an ellipsize after a maximum of 4 lines. For some reason though the rules for ellipsize don't get applied either at the Layout Preview or the actual app.
Check the screenshot below:
![Screenshot 2021-09-21 at 10 56 37 AM](https://user-images.githubusercontent.com/3630219/134142463-47379f1f-3843-4926-bf52-34a8ea3319e5.png)

Notice that the top TextView shows the proper ellipsize while the SocialTextView below doesn't apply it.

What am I doing wrong? Should I add any customisation to the SocialTextView or the helper class in order to support ellipsize as well?

**Comment by OneManStudioDotSe** [comment]
Any news on the issue?

I still haven't managed to find a way to support ellipsize at a SocialTextView and I haven't found anything at the open or closed issues.

**Comment by hendraanggrian** [comment]
Sorry for late reply. I honestly haven't touched ellipsize feature in TextView, so I can't say for sure why is this happening.

However, I did test a method from https://github.com/chrisjenx/Calligraphy/issues/43:

```java

**Comment by hendraanggrian** [comment]
Closed for inactivity.
