### ISSUE TITLE
Issues with listeners

### ISSUE THREAD

**Issue by sharmamohit096** [hendraanggrian/socialview#116]
If there are mentions users or hash or simple text all are present in and I want all separate clicks on simple text mentions and hash. SetOnClick  and other listener all will execute at the same time.

**Comment by arthtilva** [comment]
did you got solution for this? as its calling click listener also along with mention and hashtag listener.

**Comment by hendraanggrian** [comment]
I don't quite understand this. You can already `setOnHashtagClickListener` and `setOnMentionClickListener`, both require `SocialView.OnClickListener`.

Or perhaps, do you mean you have a custom `View.OnClickListener` that inadvertently triggers `SocialView.OnClickListener`?

**Comment by hendraanggrian** [comment]
Closed for inactivity.
