### ISSUE TITLE
Failed to resolve: com.hendraanggrian.appcompat:socialview:0.2

### ISSUE THREAD

**Issue by vabbydante** [hendraanggrian/socialview#117]
I am getting this error while using your dependency in Android Studio 211
gradle version : 7.3

Error is : 
Failed to resolve: com.hendraanggrian.appcompat:socialview:0.2
Failed to resolve: com.hendraanggrian.appcompat:socialview-commons:0.2

**Comment by MoaazElneshawy** [comment]
I found an old version and it works fine 
implementation "com.hendraanggrian:socialview-core:0.18"

**Comment by hendraanggrian** [comment]
The old versions were published to jcenter, I have to start again with 0.1 now that it is published to Maven Central.
