### ISSUE TITLE
Not able to import com.hendraanggrian.appcompat:socialview:0.3-rc1 and common dependency to my project

### ISSUE THREAD

**Issue by Mahantesh-Robosoft** [hendraanggrian/socialview#119]
Need to access social view in my project and i imported both library(shared below). Dependencies are not downloaded. Please help me to solve the issue? 

Is there any link with importing appcompat theme in project?

implementation("com.hendraanggrian.appcompat:socialview:0.3-rc1")
implementation("com.hendraanggrian.appcompat:socialview-commons:0.3-rc1")

in buildscript scope: 

 repositories {
        google()
        mavenCentral()
    }

compileSdk = 32
minSdk = 23
targetSdk = 32

@hendraanggrian , @stanbar , @uzaysan , Please help me with this

**Comment by dungly7929** [comment]
same as me can't import

**Comment by Dheeru1939** [comment]
where u able to find any solution or any alternative for this problem

**Comment by hendraanggrian** [comment]
There is only snapshot version, it is listed in the README. Refer to [OSSRH guide](https://central.sonatype.org/publish/publish-guide/) for using snapshot version.
