### ISSUE TITLE
Mentions working only once

### ISSUE THREAD

**Issue by sfucko** [HendraAnggrian/socialview#12]
Hello, my friend. Thanks for your lib, it is very usefull, but when i tyiping text and use mention, I cant see the list of mentions when I write @ for second time

**Comment by HendraAnggrian** [comment]
Hi @sfucko, I am unable to reproduce the error. Would you mind telling me the detailed steps you have taken to achieve the error?

In the meantime, I am in the process of reverting majority of my libraries to Kotlin, this library is one of them. It shouldn't be a problem if you're using Java, but I thought you should know.

**Comment by CripyIce** [comment]
Hi there, I encountered this issue too.
If you'll mention someone at the beginning of the sentence (AutoCompleteTextView is empty) and then immediately mention someone else it won't show you suggestions.

**Comment by sfucko** [comment]
Hello, here is screenshot where first mention isn't at the begining but
second isnt working

10 июля 2017 г. 8:17 пользователь "CripyIce" <notifications@github.com>
написал:

**Comment by sfucko** [comment]
10 июля 2017 г. 12:36 пользователь "Владимир Подлипняк" <
v.podlipnyak@gmail.com> написал:

**Comment by HendraAnggrian** [comment]
@CripyIce @sfucko okay I can see the problem and version 0.15.0 should fix this issue. It is also the first version fully written in Kotlin. There's also example app in java, equivalent to that in Kotlin.

Now naturally, this thing requires more testing now. I really appreciate you guys helping and let me know if I can be any of help.
