### ISSUE TITLE
Not Able to Import Social View

### ISSUE THREAD

**Issue by PiyushVerma26** [hendraanggrian/socialview#120]

**Comment by rajeshgupta21** [comment]
Same here! Which version should be mentioned while importing?

**Comment by syedjawadalam** [comment]
same issue

**Comment by Fr4nc1e** [comment]
Have u guys solved the problem? same issue

**Comment by tushartomarsrm** [comment]
version please !

**Comment by tushartomarsrm** [comment]
version please !

**Comment by abhishekrajput123** [comment]
same issue

**Comment by hendraanggrian** [comment]
Since jcenter is deprecated, version 0.1-SNAPSHOT is released to Maven Central. Add `https://s01.oss.sonatype.org/content/repositories/snapshots/` to your buildscript to import them.
