### ISSUE TITLE
I am not able to  find Version.

### ISSUE THREAD

**Issue by abhishekrajput123** [hendraanggrian/socialview#126]
Hi all,

I am not able to  find Version.
implementation "com.hendraanggrian.appcompat:socialview-core:0.18" // base widgets
    implementation "com.hendraanggrian.appcompat:socialview-commons:0.18" // auto-complete EditText
![Capture](https://user-images.githubusercontent.com/40626335/236267312-c4b2b8f0-5143-4051-aa5c-ce231585b1b2.PNG)

Please help me

**Comment by hendraanggrian** [comment]
Since jcenter is deprecated, the library is uploaded to Maven Central as 0.1-SNAPSHOT.

**Comment by abhishekrajput123** [comment]
Hi Hendraanggrian,

I check but version number required to import library please provide
version number


Thanks & Regards
Abhishek Rajput
