### ISSUE TITLE
can not find version how i use it plz tell someone iam get stucked

### ISSUE THREAD

**Issue by suvendu021** [hendraanggrian/socialview#127]

**Comment by hendraanggrian** [comment]
There is only snapshot version, it is listed in the README. Refer to [OSSRH guide](https://central.sonatype.org/publish/publish-guide/) for using snapshot version.

**Comment by suvendu021** [comment]
sorry for interuption,can you tell the exact version i can't get it plz

**Comment by hendraanggrian** [comment]
Version 0.1 is published to Maven Central, check badges on README for the link.
