### ISSUE TITLE
what is wrong plz tell

### ISSUE THREAD

**Issue by suvendu021** [hendraanggrian/socialview#129]
![Screenshot (7)](https://github.com/hendraanggrian/socialview/assets/102411414/0eb141a5-a223-48aa-ab4d-7ec3ed50860c)
![Screenshot (8)](https://github.com/hendraanggrian/socialview/assets/102411414/2d69897e-5477-4a6e-b2d2-45502f2e8f86)
![Screenshot (6)_LI](https://github.com/hendraanggrian/socialview/assets/102411414/55e9396b-ef7f-4620-81b0-43c2ca54f5b6)

**Comment by hendraanggrian** [comment]
If you want to use SNAPSHOT version, you have to include Maven Central snapshot repository URL.

Otherwise, version 0.1 is published to Maven Central.
