### ISSUE TITLE
Mentions with different languages

### ISSUE THREAD

**Issue by sfucko** [HendraAnggrian/socialview#13]
Hello, my friend. Thanks for your work. I have some problems, with mentions on other languages. For example I need to click on @Андрей mention, but on text view it looks like simple text, so I cant click on it. Can you fix it?

**Comment by HendraAnggrian** [comment]
I suppose I could, if only I'm familiar with Russian name customs. I kind of need your help for this one, can you round up **all Russian characters** (like `н`, `д`, `й`), and some Russian common names just for test cases?

**Comment by sfucko** [comment]
Hi, here all characters of russian and names
Name: Андрей, Владимир, Дмитрий, Вова, Саша
Upper case: *АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ*

Lower case:
*абвгдеёжзийклмнопрстуфхцчшщъыьэюя*


14 июля 2017 г. 2:36 пользователь "Hendra Anggrian" <
notifications@github.com> написал:

I suppose I could, if only I'm familiar with Russian name customs. I kind
of need your help for this one, can you round up *all Russian characters*
(like н, д, й), and some Russian common names just for test cases?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HendraAnggrian/socialview/issues/13#issuecomment-315230039>,
or mute the thread

**Comment by HendraAnggrian** [comment]
Noted, I'll work on it and I'll post you back within days.

**Comment by HendraAnggrian** [comment]
@sfucko Hi there, can you do me a favor again? Would you mind pull the latest code and try it with as many Russian sentences as you could. I have updated the regex to accept more characters and it's working quite well in my test case, but I really need more tests before I push the update.

**Comment by sfucko** [comment]
Sorry, I can`t pull(
can you update and then if there are some troubles here you will revert changes, please

**Comment by HendraAnggrian** [comment]
@sfucko to make it easier I've pushed [example apk](https://github.com/HendraAnggrian/socialview/raw/master/example/example-debug-0.1.apk). Can you please try it and let me know if it works with Russian characters?

**Comment by sfucko** [comment]
yes, of course my friend:)

18 июля 2017 г. 12:06 пользователь "Hendra Anggrian" <
notifications@github.com> написал:

**Comment by sfucko** [comment]
I`ve tested it, it works well. You can update version:) Thank you

**Comment by sfucko** [comment]
Can you update faster. I have deadline, so I need to do it for tommorow.
Please

**Comment by HendraAnggrian** [comment]
In a road, will do it once I get home.

**Comment by HendraAnggrian** [comment]
@sfucko version 0.15.1 is out with this regex, thanks for your help!
