### ISSUE TITLE
Clickable Link, How to click link using this library

### ISSUE THREAD

**Issue by amirisback** [hendraanggrian/socialview#133]
Hello Hendra Anggrian
Cannot click link

im using in XML
android:autoLink="web"

in kotlin file
tv.isHyperlinkEnabled = true

still not working

**Comment by hendraanggrian** [comment]
Sorry for late reply. There is a function to `setHyperlinkClickListener`, let me know if it doesn't work on your device.

**Comment by amirisback** [comment]
thanks already work properly, thank you so much
