### ISSUE TITLE
What is the problem 

### ISSUE THREAD

**Issue by tusharuit25** [HendraAnggrian/socialview#16]
Error:Could not find com.android.support:appcompat-v7:26.0.0.
Required by:
    xxxandroid:app:unspecified
    xxxandroid:app:unspecified > com.hendraanggrian:socialview-core:0.16.0

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by HendraAnggrian** [comment]
@tusharuit25 may I see your build.gradle files? This library uses support lib version 26.0.0, which only available with Google's maven, so your build.gradle file must look like:

```gradle
repositories {
    maven { url 'https://maven.google.com' }
    jcenter()
}

dependencies {
    compile 'com.hendraanggrian:socialview-commons:0.16.0'
}
```

**Comment by tusharuit25** [comment]
maven { url "https://jitpack.io" }
    maven { url 'https://maven.google.com' }

    both works together ?

**Comment by HendraAnggrian** [comment]
@tusharuit25 yes, both works together. Are you still unable to import `socialview-commons`? There's not much I could do without seeing your full gradle files.

**Comment by tusharuit25** [comment]
I am successfully did it .
Problem with getting selected objects back
Like with custom adapter .

**Comment by HendraAnggrian** [comment]
Thank you for confirming, I'm closing this issue and I'll reply your concern in the other thread you just opened.

**Comment by tusharuit25** [comment]
Thank you so much
