### ISSUE TITLE
How to get custom object of All mentions ? like Person id and Person Name

### ISSUE THREAD

**Issue by tusharuit25** [hendraanggrian/socialview#17]

**Comment by HendraAnggrian** [comment]
I'm sorry to tell you that this feature isn't implemented yet. Although it is not impossible to do so, there are a few caveats to note:
 1. If implemented, this feature will only make sense in `socialview-commons`
 2. Getting these custom objects will ignore hashtags/mentions not selected from the adapter.
 3. Not everyone might need this feature.

I'll keep this issue open for more input.

**Comment by tusharuit25** [comment]
This feature is needed because programmer might need to send who are those which are mentioned while typing text and need to send some notifications to them explicitly that you are mentioned at least need id.

**Comment by HendraAnggrian** [comment]
I could run a few tests first to see how reliable this feature could be. How urgent do you need this feature?

**Comment by tusharuit25** [comment]
I used your component it work like butter ; I would appreciate if you can just let me know how to get selected item (object) which we select it from autocomplete suggestions.
I have 3 days time to complete this feature in my project.

**Comment by HendraAnggrian** [comment]
I could write some functions right now before this feature is fully implemented. Are you writing the project in Java/Kotlin? If it is Java, do you have access to lamdba (Java 8)? Do you use RxJava by any chance?

**Comment by tusharuit25** [comment]
Its JAVA at my end ; plane java

**Comment by HendraAnggrian** [comment]
Change `Mention` to your custom object:
```java
@NonNull
public Collection<Mention> getMentionObjects(@NonNull SocialAutoCompleteTextView textView) {
    Collection<Mention> objects = new ArrayList<>();
    ArrayAdapter<Mention> adapter = (ArrayAdapter<Mention>) textView.getMentionAdapter();
    for (String mention : textView.getMentions()) {
        for (int i = 0; i < adapter.getCount(); i++) {
            Mention object = adapter.getItem(i);
            if (mention.equals(object.getUsername())) {
                objects.add(object);
            }
        }
    }
    return objects;
}
```

It's not the best approach, use it only if you are that urgent.

**Comment by tusharuit25** [comment]
Ok Thank you @HendraAnggrian

**Comment by HendraAnggrian** [comment]
@tusharuit25 You're very much welcome. I'll update this thread for future progress of this feature, thank you for your suggestion!

**Comment by MuhammadFarazAhmed** [comment]
how to set listners to when mention is clicked
i want to send id when user click on mention

**Comment by AshaChaparala** [comment]
I want to get mention id when 
User click on mention,I have tried a lot but no luck......
Can you please tell me how to achieve this ...

**Comment by tusharuit25** [comment]
@hendraanggrian I strongly recommend that your `Mention` object should contain Id

**Comment by AhmadIzaz** [comment]
@MuhammadFarazAhmed did you find any to find the click listener of mentioned object from the list ??

**Comment by AhmadIzaz** [comment]
@hendraanggrian I want to know the click event  when user click on the item of dropdown. Is there any way ??

**Comment by hardikJoshi123** [comment]
Suppose I taged 10 users within post. How to get ID of clicked taged item? Suppose : 

 Hi @Hardik How are you? @Peter 
 
  Tapping on @Hardik I need to get his user ID and redirect to his profile. 

 Is this achievable with this library?

**Comment by tusharkshirsagar2021** [comment]
```
@NonNull
public Collection<Mention> getMentionObjects(@NonNull SocialAutoCompleteTextView textView) {
    Collection<Mention> objects = new ArrayList<>();
    ArrayAdapter<Mention> adapter = (ArrayAdapter<Mention>) textView.getMentionAdapter();
    for (String mention : textView.getMentions()) {
        for (int i = 0; i < adapter.getCount(); i++) {
            Mention object = adapter.getItem(i);
            if (mention.equals(object.getUsername())) {
                objects.add(object);
            }
        }
    }
    return objects;
}
```

**Comment by hardikJoshi123** [comment]
![Screenshot 2021-07-27 at 12 44 19 PM](https://user-images.githubusercontent.com/2733493/127111909-4c7a183f-86d1-4609-ac75-8ec5ed511587.png)


Hi Tushar. Thanks for your quick reply. Actually I am using SocialTextView to display post description in Recycleview. Now I am trying to grab user's ID whenever user tap on any tagged user in that post. I tried to use above method which you shared. But its giving me error. Would you please help?

**Comment by hardikJoshi123** [comment]
> I want to get mention id when
> User click on mention,I have tried a lot but no luck......
> Can you please tell me how to achieve this ...

Any idea on this?  @hendraanggrian

**Comment by hendraanggrian** [comment]
> how to set listners to when mention is clicked
> i want to send id when user click on mention

You could do it with `textView.setOnMentionClickListener`.

**Comment by hendraanggrian** [comment]
> @hendraanggrian I strongly recommend that your `Mention` object should contain Id

`Mention` is not mandatory, but the interface `Mentionable` is. The unique id is `getUsername`.

**Comment by hendraanggrian** [comment]
> @hendraanggrian I want to know the click event when user click on the item of dropdown. Is there any way ??

This isn't a supported behavior by `MultiAutoCompleteTextView`, which is a direct superclass of `SocialAutoCompleteTextView`. I'm sorry.

**Comment by hendraanggrian** [comment]
> Suppose I taged 10 users within post. How to get ID of clicked taged item? Suppose :
> 
> Hi [at]Hardik How are you? [at]Peter
> 
> Tapping on [at]Hardik I need to get his user ID and redirect to his profile.
> 
> Is this achievable with this library?

Now let us go through this scenario for a moment. The id (or in this case, `Mentionable.getUsername`) is only present when you are picking those mentions from dropdownlist with `SocialAutoCompleteTextView`. If by any chance you are manually typing those mentions, the library has no idea of knowing their ids.

I'm not saying that this feature is unachievable. It's just add a bulk of logic to what is supposed to be a simple library.

**Comment by hendraanggrian** [comment]
Closed for inactivity.
