### ISSUE TITLE
Add Text to SocialTextView

### ISSUE THREAD

**Issue by fbormann** [hendraanggrian/socialview#20]
Is there an easy way to "setText" on SocialTextView? I haven't found any.

**Comment by CripyIce** [comment]
Hey there, what do you mean by easy way to set text?

**Comment by fbormann** [comment]
Like, I couldn't find in the documentation how I could .addHashtag(String tag) to a SocialTextView nor in the source code.

**Comment by hendraanggrian** [comment]
`SocialTextView` is an extension of `TextView`, you may modify its content just like you would on a regular `TextView`. Adding `Mention` or `Hashtag` only make sense if you're using `SocialAutoCompleteTextView`.
