### ISSUE TITLE
Bug on Text Matcher

### ISSUE THREAD

**Issue by mu-hasan** [hendraanggrian/socialview#22]
When I have text "user@gmail.com", it will have 2 listener:
- @gmail for mention type
- gmail.com for hyperlink type

I think your regex to matching the text must be refine with whitespace prefix. For example:
- hello @username => it will be found as mention
- hello@username => it won't
- check it on google.com => found as hyperlink
- email me at user@google.com => not found as hyperlink

**Comment by hendraanggrian** [comment]
It seems likely, I'd say with confidence that text watcher is the most unstable feature of this library, as pointed out with [this issue I opened](https://github.com/hendraanggrian/socialview/issues/7). I will be enhancing this feature in coming days (if not weeks), I'll refer this issue in near future when I test it. In the meantime, more test cases would help.

**Comment by hendraanggrian** [comment]
Closed due to inactivity.
