### ISSUE TITLE
Handle mentions with spaces

### ISSUE THREAD

**Issue by mohsinnaqvi** [hendraanggrian/socialview#25]
How do i be able to handle mentions with spaces

Input: @moh
Suggestions: "mohsin abbas", "mohsin naqvi", "syed mohsin"
after selection it breaks at space.

If I use the displayName and userName prop, Firstly it shows in view which is not cool

All I want is it somehow after selection it shows as one mention including space.

Thanks

**Comment by rahulvis** [comment]
please help me ..? Firstname Lastname how to give  white space  as like Suggestions: "mohsin abbas", "mohsin naqvi", "syed mohsin"

**Comment by hendraanggrian** [comment]
That is an expected behavior since I thought it is generally accepted that username can't have spaces, is it not?

**Comment by mohsinnaqvi** [comment]
Its a great piece of code you have written, very help. thanks. but there 
are few platform which allow usernames with spaces while tagging like 
facebook.

**Comment by arjaywalter** [comment]
Hi @hendraanggrian I think what @mohsinnaqvi is trying to say is like the mention from facebook where in it displays the full name of the user. Would that be possible? Thanks in advance.

**Comment by AhmadIzaz** [comment]
@hendraanggrian Can you please let me know this library handling mentions with spaces or not still ? 
Thanks

**Comment by doanngoctu95** [comment]
@hendraanggrian Can you please let me know this library handling mentions with spaces or not still ?
Thanks

**Comment by hendraanggrian** [comment]
I still don't completely understand what the goal is here. But I'll make an attempt: when a hashtag symbol is typed and the adapter pops out, you guys want to search by display name instead of username?

I'm sorry in advance because I don't use Facebook nowadays, I have no idea how they work.

**Comment by doanngoctu95** [comment]
@hendraanggrian yes, can you support me about this issue or suggest me sth to resolve this?

**Comment by hendraanggrian** [comment]
You may create a custom regex to catch mention strings that can have whitespace, and set it using `textView.setMentionPattern(String)`. Unfortunately, I'm not a regex expert and can't help you much.
