### ISSUE TITLE
colors change

### ISSUE THREAD

**Issue by mahmoud939** [hendraanggrian/socialview#26]
1)- How to prevent HashTag text color and mention text color from changed until i found that mention in the DataBase

**Comment by hendraanggrian** [comment]
Hi @mahmoud939 , I'm gonna need more detailed explanation (and probably example) to truly understand your goal.

**Comment by AldioFirando** [comment]
Actually I need this answer too @hendraanggrian , In this case I want the mention color changed just if I choose from suggestion box. So if I mention user that not in dialog box, it still a normal text and not a mention text.

Thanks

**Comment by hendraanggrian** [comment]
Okay I can see your point. But I need to know if such behavior can also be expected in social media nowadays. Let's pick Twitter for example, can you mention a non-existent user? I don't have Twitter I can't really test it myself.

I just want to make sure that if we do implement that feature, it still follows social media standards/guidelines.

**Comment by v1pu2** [comment]
Actually I need this answer too @hendraanggrian , In this case I want the mention color changed just if I choose from suggestion box. So if I mention user that not in suggestion box, it still a normal text and not a mention text. If I type email id, not used mention color after @. I want this feature like WhatsApp.

Thanks

**Comment by hendraanggrian** [comment]
I believe in the newer version, you can simply `setHashtagEnabled(Boolean)` or `setMentionEnabled(Boolean)`.
