### ISSUE TITLE
Conflict with other library

### ISSUE THREAD

**Issue by Rakhimjon** [hendraanggrian/socialview#28]
I can't use with https://github.com/bravoborja/ReadMoreTextView library. Your library was removing click function from more text
![screenshot_2017-11-01-11-47-37](https://user-images.githubusercontent.com/22024327/32263809-3d927f42-befd-11e7-87fa-6872a50d2784.png)

**Comment by Rakhimjon** [comment]
I've commented one line from your code and it works.
`override fun colorize() {
        val spannable = view.text
        check(spannable is Spannable, { "Attached text is not a Spannable, add TextView.BufferType.SPANNABLE when setting text to this TextView." })
        spannable as Spannable
//        spannable.removeSpans(CharacterStyle::class.java)
        if (isHashtagEnabled) {
            spannable.putSpansAll(SocialView.HASHTAG_PATTERN, {
                mHashtagListener?.newClickableSpan(spannable, mHashtagColor) ?: ForegroundColorSpan(mHashtagColor.defaultColor)
            })
        }
        if (isMentionEnabled) {
            spannable.putSpansAll(SocialView.MENTION_PATTERN, {
                mMentionListener?.newClickableSpan(spannable, mMentionColor) ?: ForegroundColorSpan(mMentionColor.defaultColor)
            })
        }
        if (isHyperlinkEnabled) {
            spannable.putSpansAll(SocialView.HYPERLINK_PATTERN, {
                mHyperlinkListener?.newClickableSpan(spannable, mHyperlinkColor, true) ?: object : ForegroundColorSpan(mMentionColor.defaultColor) {
                    override fun updateDrawState(ds: TextPaint) {
                        super.updateDrawState(ds)
                        ds.isUnderlineText = true
                    }
                }
            })
        }
    }`
Maybe it's wrong. Why you removing clickable spans?

**Comment by hendraanggrian** [comment]
Pardon my slow learning, I fail to understand what you're trying to achieve here. That `removeSpans` is necessary to clear up old spans before adding new ones.

**Comment by hendraanggrian** [comment]
Closed due to inactivity.
