### ISSUE TITLE
filtering is not happen.

### ISSUE THREAD

**Issue by kashifansari786** [hendraanggrian/socialview#31]
first of all this is great library , so thanks for this.
so the prob is in hashtag list there is no "#" is shown and if i get module from your library to change manually then some files are not downloaded from github so that i m not able to import your module, and second prob is that if i want only than hashtag and mention person which starting letter and ending letter is that(like example "k") so that is not happen it search all data which contain that letter. so if you help me in that it will appreciated .

**Comment by hendraanggrian** [comment]
I'm having a hard time understanding your goals. Would you please elaborate? Will be much better with examples.

**Comment by kashifansari786** [comment]
ok sorry for my english , i have problem which is listed below:
1)i want to import your library in my project as a module, the prob is that when i import your library it stuck on gradle and show error at GitHub link which is  not found by studio.
2)i want to filter hashtags data only that data which start with any letter which i typed in edittext, your library is filter data when i typed any letter in edittext and that letter is exist anywhere in the sentence i want filter that data which start that particular letter only.
3)i want to remove hashtag from list populating when letter is typed.
4)you have not clearly elaborate custom adapter please elaborate custom adapter with example.

thanks you hope you will understand my problem and thanks for this beautiful library.

**Comment by hendraanggrian** [comment]
1. The repositories are now hosted in maven central.
2. I'm sorry I'm still having trouble understanding this, a step-by-step example would be helpful.
3. This is currently only possible by `textView.setHashtagAdapter(newAdapter)`.
4. Custom adapter are now well-documented in README.

**Comment by hendraanggrian** [comment]
Closed for inactivity.
