### ISSUE TITLE
results continue to filter even after 

### ISSUE THREAD

**Issue by virengujariya** [hendraanggrian/socialview#32]
I am using own adapter and filtering logic

So once I type `@` or `#` it will popup results, however once I select an item and continue to type regular caption, it still is trying to filter results

**Comment by hendraanggrian** [comment]
May I see your custom adapter code?

**Comment by Drakot** [comment]
I assure this is still happening. after selecting a result type a letter and it will trigger the setMentionTextChangedListener

**Comment by FidaMOhsin** [comment]
@virengujariya was asking write. can you check please @hendraanggrian ?

**Comment by hendraanggrian** [comment]
Closed for inactivity.
