### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AshaChaparala** [hendraanggrian/socialview#34]
First of all Thank you for creating such a awesome library.
can you please tell me how to get mention id onclick on Mention and I want to allow spaces for mention.
Can you guide me how can I achieve it?
I have tried a lot but didn't get any solution....

**Comment by hendraanggrian** [comment]
Sorry for late reply.

Usernames generally don't allow spaces and I intend to keep it that way.

About getting mention ID, I've been getting more and more similar requests. I might support it in future releases. But for now, you have to manually find the object given string result provided.
