### ISSUE TITLE
Not working for android oreo that is 8,1.1

### ISSUE THREAD

**Issue by abhyag** [hendraanggrian/socialview#35]
Hi
Can you please check that the commons "mention" is not displaying the recommended box in android 8.1.1 i.e oreo but working in other versions
thanks

**Comment by hendraanggrian** [comment]
Can you please specify on what ROM are you? Because my AVD on 8.1.1 works just fine.

**Comment by abhyag** [comment]
hi thanks for replying...i am running it on google pixel device and even tried on emulator with api 27 
. Thanks.

**Comment by hendraanggrian** [comment]
Sorry for late reply. I'm pretty sure it should work since I tried it on AVD 27. Try the newest version `0.18` and let me know how it goes.

**Comment by abhyag** [comment]
hey thanks will check and let u know.

**Comment by devingDev** [comment]
Title should maybe be more descriptive than "not working" like adding  "Mention box is not showing on Android 8.1.1" . Because I thought when I saw the title the whole library is not working at all.
Anyways seems like this was fixed? It works on my emulator with API 27

**Comment by hendraanggrian** [comment]
Feel free to reopen this issue when more information about the error is available.
