### ISSUE TITLE
app:socialEnabled is not found error in gradle build.

### ISSUE THREAD

**Issue by nivid12** [hendraanggrian/socialview#37]
I cannot find this attribute while building the project. Help!!!

**Comment by fukemy** [comment]
hi, did u solved this?

**Comment by nivid12** [comment]
Hi, I didn't. I ended up making it from the scratch.

**Comment by hendraanggrian** [comment]
It has been changed to 'socialFlags' I don't remember since what version. These kind of information can be easily obtained in `attrs.xml`.
