### ISSUE TITLE
hashtag and mention filter logic.

### ISSUE THREAD

**Issue by kashifansari786** [hendraanggrian/socialview#38]
thank you so much for sharing such a excellent library it really helped me alot but i need your support to filter hashtag and mentions in such a way that enter text should matched from the beginning and not from anywhere in the text also please help me to understand that how can i display the list of hashtags with a # character assign to it  at the beginning .and if you have Java version of this library then please share with me it really helped me . Thank you so much

**Comment by hendraanggrian** [comment]
I'm having difficulties understanding your goal here. I'll make it point to point:
 1. I don't understand what you mean by "matched from the beginning and not from anywhere in the text". Please elaborate.
 2. About showing suggestions as soon as you type '#'. I'm sorry to tell you that the minimum threshold for `AutoCompleteTextView` is 1. There might be some workaround (which includes increasing a lot of codebase), but I just don't know yet if it is worth a feature that not everyone might need.
 3. As of Java version of this library. No. I'm sorry for more dependency for non-Kotlin projects.

**Comment by hendraanggrian** [comment]
Closed due to inactivity.
