### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by cengizozcan** [HendraAnggrian/socialview#4]
Hello, can you add url property ?

**Comment by hendraanggrian** [comment]
@cengizozcan I don't quite understand what you want to do with that url. If you mean url of user avatar in mention adapter, it is already supported, check [here](https://github.com/hendraanggrian/socialview/blob/master/socialview-demo/src/main/java/io/github/hendraanggrian/socialviewdemo/SuggestionFragment.java) to see how it is used.

**Comment by cengizozcan** [comment]
@hendraanggrian i mean handling url text like mention. When string includes url text, users can click on it.

**Comment by hendraanggrian** [comment]
@cengizozcan this is actually a good idea, I have uploaded version 0.4.0 to support hyperlink. Keep in mind that this feature, including the entire library itself, is still in preview until version 1.0.0.
