### ISSUE TITLE
Add Support for RichTextFormatting

### ISSUE THREAD

**Issue by wanclem** [hendraanggrian/socialview#40]
Hello, nice library here. I wanted to ask if it's possible to add support for rich text formatting like on WhatsApp and Slack such that when a user types any group of words between *here* it becomes bold and _here_ becomes italic...

**Comment by hendraanggrian** [comment]
Thanks!

Though it's very much possible and can be easily implemented (given that pattern and colorizing logic is already there), I'm not sure if this is needed. Most social media text fields do not support this behavior, expect if we're talking about online forums.

But this library is always open for improvement, let's wait for others' input on this.

**Comment by devingDev** [comment]
Sounds nice but it should be togglable.

**Comment by FidaMOhsin** [comment]
Hi @hendraanggrian
Can you please tell me have you fixed this issue?

**Comment by NehaKushwah993** [comment]
this html is not working

**Comment by hendraanggrian** [comment]
I believe hyperlink colorization is working and configurable now, so I'm closing this issue.

**Comment by guizot** [comment]
Bro bagimana ya caranya supaya bisa **bold text**  menggunakan **SocialTextView**? saya pakai **Html.fromHtml** tapi tidak bold text nya?

**Comment by hendraanggrian** [comment]
@guizot Malam bang. Karena semua `TextView` yang implementasi `SocialView` akan reset spanning setiap text berubah, bold spanningnya mesti manual di `TextWatcher`:

```kotlin
textView.addTextChangedListener {
    (textView.text as Spannable).setSpan(StyleSpan(Typeface.BOLD), start, end, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
}
```

**Comment by guizot** [comment]
Implementasinya gmn ya bro?

ini XML saya
> ```kotlin
> <com.hendraanggrian.appcompat.widget.SocialTextView
>                     android:id="@+id/chat_message_text_self"
>                     android:layout_width="wrap_content"
 >                    android:layout_height="wrap_content"
>                     android:drawablePadding="8dp"
>                     app:hashtagColor="@color/colorPrimaryDark"
>                     app:mentionColor="@color/colorPrimaryDark"
>                     app:hyperlinkColor="@color/colorPrimaryDark"/>`
> ```

ini di Adapter saya
> ```kotlin
> chat_message_text_self.text = Html.fromHtml(message).trim()
> ```

Implementasi `TextWatcher ` dimana ya bro?
