### ISSUE TITLE
Cant find last version to compile project

### ISSUE THREAD

**Issue by mrb4hr4m** [hendraanggrian/socialview#45]
jow to add this project in Android Studio . please write the latest version . i checked all versions but got error

**Comment by hendraanggrian** [comment]
Sorry for the hassle, I will be updating README in following days.

**Comment by hendraanggrian** [comment]
Artifacts are up, refer to README to download latest version. Some notes:
 * AndroidX from now on.
 * Clearing gradle cache may resolve dependency conflict.

Happy coding!
