### ISSUE TITLE
Failing to add library

### ISSUE THREAD

**Issue by harshalijain** [hendraanggrian/socialview#46]
I have added following lines to my app build.gradle

    implementation "com.hendraanggrian.appcompat:socialview:0.1"
    implementation "com.hendraanggrian.appcompat:socialview-commons:0.1"

Now its throwing following error when I perform Gradle Sync

AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"C:\\Users\\User\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-1.0.0-beta01.aar\\ce72d4b1fec626ed0410db1106f23caf\\res\\values-v28\\values-v28.xml","position":{"startLine":8,"startColumn":4,"startOffset":447,"endLine":11,"endColumn":12,"endOffset":684}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"C:\\Users\\User\\Documents\\GIT\\thestarinme-app-android-intrepo\\app\\build\\intermediates\\incremental\\mergeDebugResources\\merged.dir\\values-v28\\values-v28.xml","position":{"startLine":10}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/fontVariationSettings not found.","sources":[{"file":"C:\\Users\\User\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-27.1.1.aar\\f2c84627ffa3757e7034ce359df8c894\\res\\values\\values.xml","position":{"startLine":250,"startColumn":4,"startOffset":27058,"endColumn":68,"endOffset":27122}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/ttcIndex not found.","sources":[{"file":"C:\\Users\\User\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-27.1.1.aar\\f2c84627ffa3757e7034ce359df8c894\\res\\values\\values.xml","position":{"startLine":250,"startColumn":4,"startOffset":27058,"endColumn":68,"endOffset":27122}}],"original":"","tool":"AAPT"}

Target SDK version is API 27
Android Studio version 3.1.3

Please help me with the correct implementation to include the library in my project.

**Comment by hendraanggrian** [comment]
First, make sure that you have migrated to AndroidX, not legacy support library.

**Comment by harshalijain** [comment]
Well after a lot of digging around, this solution worked for me

```
implementation 'com.hendraanggrian.socialview:socialview-commons:0.1'
implementation 'com.hendraanggrian.socialview:socialview:0.1'
```

**Comment by hendraanggrian** [comment]
@harshalijain `com.hendraanggrian.socialview` is a deprecated repository, the last one that isn't AndroidX. When you decide to use AndroidX in the future, you should use `com.hendraanggrian.appcompat`.
