### ISSUE TITLE
setMentionTextChangedListener is called just after the first char typed.

### ISSUE THREAD

**Issue by igorlopesfaria** [hendraanggrian/socialview#60]
setMentionTextChangedListener is only called after the first char typed.

after typing @x the method onChanged is printing on log "g" correctly  but if you continue to type @xeaj, the method no more is called.

**Comment by hendraanggrian** [comment]
I fear that Kotlin to Java conversion of this library isn't finished yet and still brings some bugs, rest assured I'm looking into this and will update when I have more info.

**Comment by hendraanggrian** [comment]
I'm pretty sure the conversion is complete now and should not have this problem anymore.
