### ISSUE TITLE
How to use SocialViewImpl

### ISSUE THREAD

**Issue by Vitor238** [hendraanggrian/socialview#62]
How made EmojiEditText from https://github.com/vanniktech/Emoji social using SocialViewImpl and Java?

**Comment by hendraanggrian** [comment]
Emoji is quite a different topic, but is still possible to support while also having hashtag, mention, and hyperlink spanning. 

You should create your own custom `EditText` using base code in `SocialEditText`, and from there you can somehow combine with emoji-supporting code.
