### ISSUE TITLE
When i use custom adapter, pass this

### ISSUE THREAD

**Issue by jccd1996** [hendraanggrian/socialview#64]
When i choose the person of the Mentions, pass this.
![WhatsApp Image 2019-05-09 at 17 10 37](https://user-images.githubusercontent.com/39463623/57490076-a965a480-727d-11e9-8b82-18108f0085b5.jpeg)

Then pass this, show all name literal, class, parameters and the value of parameter..., whats can i do?

![WhatsApp Image 2019-05-09 at 17 10 37 (1)](https://user-images.githubusercontent.com/39463623/57490080-abc7fe80-727d-11e9-8892-6fa0a3d9361a.jpeg)

**Comment by hendraanggrian** [comment]
To include `(name=paco)` as part of username, I think you need to write a custom regex pattern, which will be supported in upcoming version 0.3.
