### ISSUE TITLE
How do i get the response after typing?

### ISSUE THREAD

**Issue by SinanYilmaz9** [hendraanggrian/socialview#66]
I don't want to response to return while the type process is in progress. I want to get it after the typing completed (for example 200 milliseconds after stopping typing). How can i do it?

**Comment by hendraanggrian** [comment]
One way to do it is to create a thread that waits for 200 milliseconds before executing the rest of the code.

Another way might be a little bit tricky which requires your help to test, comment this thread if you're still interested.

**Comment by hendraanggrian** [comment]
Closed due to inactivity.
