### ISSUE TITLE
How do I perform query operations with spaces?

### ISSUE THREAD

**Issue by SinanYilmaz9** [hendraanggrian/socialview#67]
For example;

I don't want to **_#social#view@hendraan_**
I want to **_#social #view @hendraan _**

How can i do it?

**Comment by hendraanggrian** [comment]
I'm not sure what you intend to do with that string.

![Screenshot_1595361053](https://user-images.githubusercontent.com/11507430/88099993-2bfa2b80-cbc6-11ea-9532-d13b1d516f59.png)

**Comment by hendraanggrian** [comment]
Closed due to inactivity.
