### ISSUE TITLE
mentionAdapter and hashtagAdapter not found 

### ISSUE THREAD

**Issue by VirenderSingh123** [hendraanggrian/socialview#72]

**Comment by VirenderSingh123** [comment]
textView.hashtagAdapter = defaultHashtagAdapter
        textView.mentionAdapter = defaultMentionAdapter

**Comment by VirenderSingh123** [comment]
please provide solution

**Comment by pingothedoer** [comment]
@VirenderSingh123 I just faced this issue and found a solution in the demo of this repo. 
` val mentionAdapter: ArrayAdapter<Mention> = MentionArrayAdapter(context)`

`MentionAdapter` has been replaced with `MentionArrayAdapter`

**Comment by hendraanggrian** [comment]
Can you please post this as an issue in GitHub and I’ll try my best to help.

Thanks

**Comment by hendraanggrian** [comment]
Thanks @pingothedoer for pointing that out.
