### ISSUE TITLE
Hashtag color can't change

### ISSUE THREAD

**Issue by Shivani12345** [hendraanggrian/socialview#76]
i can't change  Hashtag color  with 
`textSocial.setHashtagColor(Color.GREEN);`
i can change Mention Color using `textSocial.setMentionColor(getResources().getColor(R.color.vermilion));`
here i found problem in SocialAutoCompleteTextView
you set wrong hashtag color,kindly please update your code 
 
>  @Override
>     public int getHashtagColor() {
>         return impl.getHyperlinkColor();
>     }

**Comment by uzaysan** [comment]
I also faceing same issue

**Comment by hendraanggrian** [comment]
Thanks for this. It is flagged as fixed in upcoming version 0.3.
