### ISSUE TITLE
Handling of hashtag click listener

### ISSUE THREAD

**Issue by purnimadan** [hendraanggrian/socialview#77]
#hashtag content - if there is some text after hashtag then it works fine. Hashtag and content click take me to two different screens.
#hashtag [space] - if there is no text after hashtag but only spaces then click on the empty area also takes me to hashtags screen. I want that space click to take me to the screen where content clicks take me.
Thanks in advance.

**Comment by androidvk** [comment]
Why don't you get the length before changing activity in onclicklistener

**Comment by hendraanggrian** [comment]
I'm not quite so sure what you're talking about here. If there is no text after hashtag symbol, then it wouldn't count as a hashtag.

![Screenshot_1595359890](https://user-images.githubusercontent.com/11507430/88098128-7928ce00-cbc3-11ea-8a70-2550e67b7ddc.png)

**Comment by hendraanggrian** [comment]
Closed due to inactivity.
