### ISSUE TITLE
Detect click event of dropdown and handle mention with spaces.

### ISSUE THREAD

**Issue by AhmadIzaz** [hendraanggrian/socialview#79]
I am trying to detect the click event when user click on any item on the dropdown.
Also I am trying to mention person with spaces in its name but this library doesnot support this and also not changing the color of that mentioned text if it contains space. e.g **@FirstName LastName.**
It will only pick the **FirstName** leaving behind the **LastName**

**Comment by hendraanggrian** [comment]
Yes I think that is by design. Username in my dictionary should be a unique identifier containing no space, I think Twitter follows this guideline as well.
