### ISSUE TITLE
Is it possible to limit usage of # ? 

### ISSUE THREAD

**Issue by ismailtosun** [hendraanggrian/socialview#80]
hi is it possible to limit usage # ? for example I want to use in my edit text max size 3 #. 

#hello #hi #ola but not let one more # adding.

please help me 
thanks

**Comment by hendraanggrian** [comment]
It is absolutely possible to limit the length of hashtag. But it will end up with users typing long hashtag where only the first N characters are colorized, which I think is a bad UI.

Alternatively, you can apply some kind of check that a hashtag is getting longer than what you expect upon text submission.
