### ISSUE TITLE
Mention suggestion problem in devices running on 8.0, 8.1, 9.0 and 10 

### ISSUE THREAD

**Issue by AbuzarJan** [hendraanggrian/socialview#81]
I am using version 0.2

**Comment by hendraanggrian** [comment]
Upon testing this library, I'm using emulator with API level 29 (Android 10). Can you elaborate what the problem is?

**Comment by FidaMOhsin** [comment]
I'm facing this error too.
When you mention a person and then clear the SocialAutoCompleteTextView. And then just write letters of previous motioned person name without @ tag, you will show a mentions list for a second.
it is same for #.
any solution?

**Comment by hendraanggrian** [comment]
@FidaMOhsin I still can't reproduce the error. What version of AndroidX and SDK are you testing it with?
