### ISSUE TITLE
Get mention user profile id

### ISSUE THREAD

**Issue by nanashili** [hendraanggrian/socialview#82]
Is it possible to get a users profile ID when mentioning user. Only way i can get the id is if i change Mention.class

`@NonNull
    @Override
    public String toString() {
        return id.toString();
    }`

but that's not what i want i want the username but when i upload it to my Firebase Database  i wanna save the username and id of the mentioned user.

**Comment by hendraanggrian** [comment]
First, actually you don't have to use `Mention`. If you have your own object, implement it with `Mentionable` and you're good to go.

At last, if I'm not mistaken you want `textView.getMentions()` to return list of mentionable object and not string. The problem with this is the textview cannot differentiate between mentions you have manually typed and mentions you click from the popup. Your popup mentions are definitely a `Mentionable` object, while your written mentions are string. There is not even a validation that mentions you type actually exists in your database.

Am I making sense to you? What do you suggest we should do?

**Comment by hendraanggrian** [comment]
Closed for inactivity.
