### ISSUE TITLE
Release new version with latest commits

### ISSUE THREAD

**Issue by uzaysan** [hendraanggrian/socialview#83]
ı see you fixed some issues. But last version is 0.2 and this version doesnt contain latest commits. Please release a new version. I tried to add your library to my project as module. But gradle build is not successful

**Comment by hendraanggrian** [comment]
My apologies for slow release cycle, I was pre-occupied with other projects. I will be prioritizing version 0.3 and it should be shipped within 1-2 days.

**Comment by uzaysan** [comment]
Great. Thank you. I'll be waiting.

One problem i noticed, socialtextview has problem. When I long click mention or hashtag etc.. app crashes. Hope you also fix that

**Comment by hendraanggrian** [comment]
That thing about unsuccessful gradle build, is it related to the newer Android gradle build tools 4.0.0? Would you kindly post your build.gradle files?

I will look into the long click issue, I believe there are also quite a few threads about it.

**Comment by uzaysan** [comment]
I dont know much. But Android studio cannot resolve build gradle.

I downloaded your library.
Extracted files into my project folder.
In Gradle setting I included your library.
Den in project level gradle ı compiled your library but No luck

**Comment by hendraanggrian** [comment]
First release candidate of version 0.3 has been out. Please test it and if there is still gradle error, please post the output here.

**Comment by uzaysan** [comment]
Hey. Thanks for update. I still get this error.

![rsz_screenshot_from_2020-07-22_00-25-06](https://user-images.githubusercontent.com/43876876/88108849-34486b80-cbb2-11ea-9b95-7457cfc4f8b7.png)


Better to add this library from gradle

**Comment by uzaysan** [comment]
@hendraanggrian Hey I downloaded source code and ried to add lbrary as module. But I see you relased 0.3-rc1. And this version works.

**Comment by nikolasamardzija** [comment]
@hendraanggrian @uzaysan How did you managed to add dependencies and build successfully?
![image](https://user-images.githubusercontent.com/23246626/89549621-d5693000-d808-11ea-9c7b-d110b1fd3975.png)

This is my project build.gradle
`buildscript {
    ext.kotlin_version = '1.3.72'
    ext.koin_version = '2.1.5'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {...`

Thanks

**Comment by fukemy** [comment]
i cant not run gradle too, version 0.3-rc1 error can not found

**Comment by hendraanggrian** [comment]
Can you make sure that JCenter is added to your repository list?

**Comment by fukemy** [comment]
it work for 
```
implementation "com.hendraanggrian.appcompat:socialview-commons:$socialview_version"
```
may be implementation "com.hendraanggrian.appcompat:socialview:$socialview_version" is removed, now im started to use your lib, thanks

**Comment by hendraanggrian** [comment]
The project has now moved to maven central, but at the moment only SNAPSHOT.

**Comment by hashop9** [comment]
if it close mean its not works
i neaded present version which is runing


implementation 'com.hendraanggrian.appcompat:socialview-core:____'
    implementation 'com.hendraanggrian.appcompat:socialview-commons:____'
    api 'com.theartofdev.edmodo:android-image-cropper:____'
