### ISSUE TITLE
Can not resolve project

### ISSUE THREAD

**Issue by WeberHsu** [hendraanggrian/socialview#84]
I have the problem when I add it to my project : 
Failed to resolve: com.hendraanggrian.appcompat:socialview-core:0.2

and I tried many versions is the same. (0.1, 0.2, 0.3 ...... and so on)

**Comment by hendraanggrian** [comment]
My bad I forgot to update the README.

`socialview-core` has been deprecated for some time, use `socialview` instead for core library. Therefore, it should be `com.hendraanggrian.appcompat:socialview-core:$latestVersion`
