### ISSUE TITLE
Need help hashtags and mension list showing behind keyboard

### ISSUE THREAD

**Issue by dhruvraval990** [hendraanggrian/socialview#88]
Hello,
Thank you so much for this library
Need help for showing list on top of  edittext 
Please help me with that.

**Comment by chrisbarth01** [comment]
The same challenge I'm facing. I've tried but no solution.

**Comment by ismaielsharif** [comment]
![1615368017573](https://user-images.githubusercontent.com/32194087/110606228-cb971900-81ab-11eb-80ca-d566636167b0.JPEG)
Here is my result.

**Comment by chrisbarth01** [comment]
Thanks @ismaielsharif I'd try this. For now, I'm trying to resolve a new bug in which the app crashes when you start typing a mention. Once it's solved, I'll see if your line of code resolves the hidden suggestion issue.

**Comment by hendraanggrian** [comment]
I'm very sorry I'm preoccupied with JVM projects for now. But if you submit a pull request I swear I'll read every line of it.

**Comment by chrisbarth01** [comment]
Well @hendraanggrian there are a few bugs. I created an issue recently, I hope that you attend to it asap as the only other option I have is to not use the socialtextview. Thanks.

**Comment by hendraanggrian** [comment]
Thanks @ismaielsharif! I would've tried something like [these](https://stackoverflow.com/questions/26401412/android-autocompletetextview-dropdown-position), but yours looks simpler and cleaner.

This kind of feature has nothing to with socialview behavior, so I'm closing this.
