### ISSUE TITLE
No Java Code for example

### ISSUE THREAD

**Issue by TheinvinciblePrints** [HendraAnggrian/socialview#9]
No java code provided for the example as it is written in Kotlin

**Comment by HendraAnggrian** [comment]
Hi, I'm sorry I was rather busy these past weeks. The java example code is provided in [README.md](https://github.com/HendraAnggrian/socialview/blob/master/README.md). Or if you are interested in particular kotlin classes in example app, pick some of them and I will convert them to java.

**Comment by sfucko** [comment]
Please, convert the 4th activity to java, because it is very usefull to show not nick name of user, but show for example Full name and surname:
not @nick1337, but @NickDylan

**Comment by HendraAnggrian** [comment]
@sfucko okay this is my bad, I should have written more about how to use custom adapter in readme. Give me a day to update it and I'll write you the java version afterwards.

**Comment by sfucko** [comment]
ok, thanks, my friend

30 июня 2017 г. 2:24 пользователь "Hendra Anggrian" <
notifications@github.com> написал:

**Comment by HendraAnggrian** [comment]
@sfucko you may look at [this test custom adapter](https://github.com/HendraAnggrian/socialview/blob/master/socialview-commons/tests/src/com/hendraanggrian/socialview/commons/test/PersonAdapter.java) and its implementation in readme. Also, make sure to use version 0.14.0.

**Comment by HendraAnggrian** [comment]
Java example module has just been added.
