### ISSUE TITLE
Type # not showing suggestion

### ISSUE THREAD

**Issue by Rajkumarrmani** [hendraanggrian/socialview#93]
Hai, First I would like to say thank you for this library. My suggestion Please keep upgrade and optimize. 

I've type "#" need to show the suggestion list - It is possible? If yes please tell me or provide some guidelines to achieve this.

Thank you.

**Comment by hendraanggrian** [comment]
Duplicate of #23.

But do try putting `android:completionThreshold="0"` on your `SocialAutoCompleteTextView` XML and see how it works.
