### ISSUE TITLE
JCenter is deprecated

### ISSUE THREAD

**Issue by vanyasem** [hendraanggrian/socialview#98]
The JCenter repository is now deprecated and will stop service on February 1, 2022. For more information, see https://developer.android.com/studio/build/jcenter-migration

**Comment by hendraanggrian** [comment]
Yes I'm aware of this. I have started the transition process of some of my libraries to Maven Central. Expect this library to be ported there as well within weeks.

**Comment by vanyasem** [comment]
@hendraanggrian bump

**Comment by hendraanggrian** [comment]
[Snapshot version](https://s01.oss.sonatype.org/content/repositories/snapshots/com/hendraanggrian/appcompat/) is released, sorry for the delay.
