### ISSUE TITLE
Change position of suggestions

### ISSUE THREAD

**Issue by muneebahmed97** [hendraanggrian/socialview#99]
How can I move autocompletetextview suggestions from bottom to top of it?
My Code: 
<RelativeLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:paddingStart="10dp"
                android:paddingTop="5dp"
                android:paddingEnd="10dp"
                android:paddingBottom="5dp">
                
                  <com.hendraanggrian.appcompat.widget.SocialAutoCompleteTextView
                    android:id="@+id/et_member_comment"
                    android:layout_width="wrap_content"
                    android:layout_height="50dp"
                    android:layout_marginStart="5dp"
                    android:layout_toStartOf="@id/btn_send"
                    android:textAlignment="viewStart"
                    android:background="@android:color/transparent"
                    android:hint="@string/write_a_comment"
                    android:lines="1"
                    android:textSize="14sp"
                    app:hashtagColor="@color/neon_yellow"
                    app:mentionColor="@color/com_facebook_blue"
                    app:socialFlags="hashtag|mention" />
                    
                    <com.skydoves.elasticviews.ElasticImageView
                    android:id="@+id/btn_send"
                    android:layout_width="30dp"
                    android:layout_height="30dp"
                    android:layout_alignParentEnd="true"
                    android:layout_centerVertical="true"
                    android:onClick="@{(v)->fragment.onSendClick()}"
                    android:padding="5dp"
                    android:src="@drawable/icon_send"
                    android:tint="@color/neon_yellow"
                    app:imageView_duration="300"
                    app:imageView_scale="0.7" />

            </RelativeLayout>

**Comment by hendraanggrian** [comment]
The drop down position of `AutoCompleteTextView` is not managed by this library. You'll probably have better luck in searching through StackOverflow on how to do it. Here's an example: https://stackoverflow.com/questions/26401412/android-autocompletetextview-dropdown-position.
